name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - master
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/release.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build RustScan
        run: cargo build --release
      - name: Package binary
        run: tar -czvf rustscan-macos-arm.tar.gz target/release/rustscan
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rustscan-macos-arm
          path: rustscan-macos-arm.tar.gz
